services:
  wallet-rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-rest-app
    ports:
      - "8080:8080"
    environment:
      COINCAP_API_KEY: ${COINCAP_API_KEY}
    restart: unless-stopped
