spring:
  application:
    name: walletrest
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
server:
  port: 8080


wallet:
  api:
    baseurl: /api/v1/wallet

coincap:
  base-url: https://rest.coincap.io/v3
  api-key: ${COINCAP_API_KEY}